--- # second playbook

- name: this playbook will install httpd package on all nodes
  hosts: all
  remote_user: ec2-user
  become: yes
  tasks: 
   - name: install httpd package
     #action: yum name=httpd state=installed
     yum:
       name: httpd
       state: present


   - name: service http start
     service:
       name: httpd
       state: started
